import { Day } from "./types";

export const programData: Day[] = [
  {
    date: "Vendredi 22 Juillet",
    events: [
      {
        kind: "show",
        time: "14h30",
        title: "C'EST ASSEZ BIEN D'ÊTRE FOU",
        author: "Antoine Page sur Bilal Berreni",
        year: 2013,
        duration: 60,
        notes: "Projection jeune public - version courte",
      },
      {
        kind: "show",
        time: "17h",
        title: "ESCHER, L'EXPLORATEUR DE L'INFINI",
        author: "Robin Lutz",
        year: 2018,
        duration: 52,
      },
      {
        kind: "show",
        time: "18h15",
        title: "MONA HATOUM AU CENTRE POMPIDOU",
        author: "Alyssa Verbizh",
        year: 2015,
        duration: 20,
      },
      {
        kind: "show",
        time: "18h45",
        title: "A CORRIGER",
        author: "Raphaël Wirth et Pierre Alexandre Cavé, sur Omar Ba",
        year: 2021,
        duration: 52,
      },
      {
        kind: "show",
        time: "20h",
        title: "GABRIELLE MÜNTER",
        author: "Florence Mauro",
        year: 2021,
        duration: 54,
      },
      {
        kind: "break",
        time: "21h",
        name: "Dîner",
      },
      {
        kind: "show",
        time: "21h",
        title: "ANNA HALPRIN, LE SOUFFLE DE LA DANSE",
        author: "Ruedi Gerber",
        year: 2009,
        duration: 80,
      },
    ],
  },
  {
    date: "Samedi 23 Juillet",
    events: [
      {
        kind: "show",
        time: "17h",
        title: "SIGNÉ DALI",
        author: "Philippe Elusse",
        duration: 52,
      },
      {
        kind: "show",
        time: "18h15",
        title: "REBECCA HORN",
        author: "Heinz-Peter Schwerfel",
        year: 1993,
        duration: 44,
      },
      {
        kind: "show",
        time: "19h15",
        title: "TERRES BARCELO",
        author: "Christian Tran",
        year: 2018,
        duration: 75,
      },
      {
        kind: "show",
        time: "20h30",
        title: "LES PLANTES QUI DANSENT",
        author: "Anita Mizrahi",
        duration: 4,
      },
      {
        kind: "show",
        time: "20h30",
        title: "MAIS AILLEURS C'EST TOUJOURS MIEUX",
        author: "Vivian Ostrovsky",
        year: 2016,
        duration: 4,
      },
      {
        kind: "show",
        time: "20h30",
        title: "SON CHANT",
        author: "Vivian Ostrovsky",
        year: 2020,
        duration: 12,
      },
      {
        kind: "break",
        time: "21h",
        name: "Dîner",
      },
      {
        kind: "show",
        time: "22h",
        title: "C'EST ASSEZ BIEN D'ÊTRE FOU",
        author: "Antoine Page sur Bilal Berreni",
        year: 2013,
        duration: 105,
      },
    ],
  },
  {
    date: "Dimanche 24 Juillet",
    events: [
      {
        kind: "show",
        time: "16h30",
        title: "SABRINA",
        author: "Léna Durr",
        year: 2022,
        duration: 20,
      },
      {
        kind: "show",
        time: "17h",
        title: "QUE VIVA TINA",
        author: "Silvano Castano",
        year: 1997,
        duration: 52,
      },
      {
        kind: "show",
        time: "18h10",
        title: "BIENVENUE HARKIS D'AUJOURD'HUI",
        author: "présenté par Anita Mizrahi",
        year: 2022,
        duration: 52,
        notes: "Rencontre avec la réalisatrice",
      },
      {
        kind: "show",
        time: "19h15",
        title: "SHIGERU BAN, ARCHITECTE DE L'URGENCE",
        author: "Michel Quinejure",
        year: 2000,
        duration: 52,
      },
      {
        kind: "break",
        time: "20h30",
        name: "Dîner",
      },
      {
        kind: "show",
        time: "22h30",
        title: "NO LAND'S SONG",
        author: "Ayat Najafi",
        year: 2014,
        duration: 91,
      },
    ],
  },
];
